<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>jumble: Random assignment • jumble</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="jumble: Random assignment">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">jumble</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.0.2</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/01-mahalanobis.html">jumble: Mahalanobis distance</a>
    </li>
    <li>
      <a href="../articles/02-rerand.html">jumble: Re-randomization approach</a>
    </li>
    <li>
      <a href="../articles/03-assignment.html">jumble: Random assignment</a>
    </li>
    <li>
      <a href="../articles/04-stratification.html">jumble: Stratified Randomization</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/kmcconeghy/jumble">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>jumble: Random assignment</h1>
                        <h4 class="author">Kevin W. McConeghy</h4>
            
            <h4 class="date">2019-07-04</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/kmcconeghy/jumble/blob/master/vignettes/03-assignment.Rmd"><code>vignettes/03-assignment.Rmd</code></a></small>
      <div class="hidden name"><code>03-assignment.Rmd</code></div>

    </div>

    
    
<p>Welcome to jumble! This program was written as a companion to academic work performed by researchers at Brown University to conduct re-randomization for cluster-randomized nursing home trials.</p>
<div id="introduction" class="section level2">
<h2 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h2>
<p>In this vignette we demonstrate some functions used for random assignment, following best practices outlined by other R packages like randomizeR, randomizr etc.</p>
<ol style="list-style-type: decimal">
<li>Randomization must be transparent</li>
<li>Randomization must be reproducibile</li>
<li>Randomization must be random!</li>
</ol>
<div id="example-dataset" class="section level3">
<h3 class="hasAnchor">
<a href="#example-dataset" class="anchor"></a>Example dataset</h3>
<p>The example dataset used in this package is freely available and comes from a clinical HIV therapy trial conducted in the 1990s.<span class="citation">(Hammer SM 1996)</span> See: ?jumble::ACTG175</p>
<div id="load-dataset" class="section level4">
<h4 class="hasAnchor">
<a href="#load-dataset" class="anchor"></a>Load dataset</h4>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df &lt;-<span class="st"> </span>jumble<span class="op">::</span>ACTG175</code></pre></div>
</div>
</div>
</div>
<div id="a-note-on-random-number-generation" class="section level2">
<h2 class="hasAnchor">
<a href="#a-note-on-random-number-generation" class="anchor"></a>A note on random number generation</h2>
<p>The random sampling method underlying jumble functions is the base R function <code><a href="https://www.rdocumentation.org/packages/base/topics/sample">sample()</a></code>, <code><a href="https://www.rdocumentation.org/packages/stats/topics/Binomial">rbinom()</a></code>. While computational speed may be problematic in some cases, the base sample function is reliable, stable, and well-documented and tested.</p>
<p>The <code><a href="https://www.rdocumentation.org/packages/base/topics/sample">sample()</a></code> functions calls the default Random number generator for R, the Mershene-Twister method, which can be queried using <code>RNGKind()</code>.<span class="citation">Matsumoto and Nishimura (1998)</span></p>
<p>Current system build:</p>
<pre><code>## R version 3.6.0 (2019-04-26)</code></pre>
<pre><code>## Windows platform : x86_64-w64-mingw32/x64 (64-bit)</code></pre>
</div>
<div id="random-assignment-to-k-groups" class="section level2">
<h2 class="hasAnchor">
<a href="#random-assignment-to-k-groups" class="anchor"></a>Random assignment to K-groups</h2>
<p>Assigning treatment is easy if you want equal probability of assignment to one or more groups, without concern to final sample size in each arm, covariate balance etc.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">assign &lt;-<span class="st"> </span><span class="kw"><a href="../reference/rnd_assign.html">rnd_assign</a></span>(df<span class="op">$</span>pidnum, <span class="dv">2</span>, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/integer">as.integer</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/as.Date">as.Date</a></span>(<span class="st">'2019-06-26'</span>)))

<span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/head">head</a></span>(assign)</code></pre></div>
<pre><code>## # A tibble: 6 x 2
##      id group
##   &lt;int&gt; &lt;chr&gt;
## 1 10124 a    
## 2 10140 b    
## 3 10165 b    
## 4 10190 a    
## 5 10229 a    
## 6 10361 a</code></pre>
<p>Truly random assignment!</p>
<p>The seed is stored as a attribute</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">seed_iter &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/attr">attr</a></span>(assign, <span class="st">'seed'</span>)</code></pre></div>
<pre><code>## [1] "Randomization performed: 2019-07-04 Seed: 18073"</code></pre>
<p>Don’t lose that information! As long as you know the seed you can reproduce the randomization:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">assign &lt;-<span class="st"> </span><span class="kw"><a href="../reference/rnd_assign.html">rnd_assign</a></span>(df<span class="op">$</span>pidnum, <span class="dv">2</span>, seed_iter)

<span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/head">head</a></span>(assign)</code></pre></div>
<pre><code>## # A tibble: 6 x 2
##      id group
##   &lt;int&gt; &lt;chr&gt;
## 1 10124 a    
## 2 10140 b    
## 3 10165 b    
## 4 10190 a    
## 5 10229 a    
## 6 10361 a</code></pre>
<div id="simulation-to-demonstrate-equal-probability" class="section level3">
<h3 class="hasAnchor">
<a href="#simulation-to-demonstrate-equal-probability" class="anchor"></a>Simulation to demonstrate equal probability</h3>
<p>Perform 20,000 randomizations</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pidnum &lt;-<span class="st"> </span>df<span class="op">$</span>pidnum  

n=20000L

df_assign &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/lapply">lapply</a></span>(<span class="dv">1</span><span class="op">:</span>n, <span class="cf">function</span>(x) <span class="kw"><a href="../reference/rnd_assign.html">rnd_assign</a></span>(pidnum, <span class="dv">2</span>, 18073L<span class="op">+</span>x))

assigns &lt;-<span class="st"> </span><span class="kw">bind_cols</span>(df_assign[[<span class="dv">1</span>]][, <span class="dv">1</span>], 
                     <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/lapply">lapply</a></span>(df_assign, <span class="cf">function</span>(x) x[, <span class="dv">2</span>]))

df_assign_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">gather</span>(assigns, <span class="dt">key =</span> <span class="st">'trial'</span>, <span class="dt">value =</span> <span class="st">'group'</span>, 
                      <span class="kw">starts_with</span>(<span class="st">'group'</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(id) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="st">`</span><span class="dt">No. of trials</span><span class="st">`</span> =<span class="st"> </span>n,
            <span class="st">`</span><span class="dt">No. group 'a'</span><span class="st">`</span> =<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/sum">sum</a></span>(group <span class="op">==</span><span class="st"> 'a'</span>),
            <span class="st">`</span><span class="dt">No. group 'b'</span><span class="st">`</span> =<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/sum">sum</a></span>(group <span class="op">==</span><span class="st"> 'b'</span>),
            <span class="st">`</span><span class="dt">Prob. group = 'a'</span><span class="st">`</span> =<span class="st"> `</span><span class="dt">No. group 'a'</span><span class="st">`</span> <span class="op">/</span><span class="st"> </span><span class="kw">n</span>(),
            <span class="st">`</span><span class="dt">Prob. group = 'b'</span><span class="st">`</span> =<span class="st"> `</span><span class="dt">No. group 'b'</span><span class="st">`</span> <span class="op">/</span><span class="st"> </span><span class="kw">n</span>())

<span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/head">head</a></span>(df_assign_<span class="dv">2</span>)</code></pre></div>
<pre><code>## # A tibble: 6 x 6
##      id `No. of trials` `No. group 'a'` `No. group 'b'` `Prob. group = ~
##   &lt;int&gt;           &lt;int&gt;           &lt;int&gt;           &lt;int&gt;            &lt;dbl&gt;
## 1 10124           20000            9986           10014            0.499
## 2 10140           20000           10000           10000            0.5  
## 3 10165           20000            9997           10003            0.500
## 4 10190           20000           10003            9997            0.500
## 5 10229           20000            9997           10003            0.500
## 6 10361           20000           10001            9999            0.500
## # ... with 1 more variable: `Prob. group = 'b'` &lt;dbl&gt;</code></pre>
<p>First glance shows ~ equal likelihood of group assignment in 20,000 trials. ### Assignment tests<br><img src="03-assignment_files/figure-html/unnamed-chunk-10-1.png" width="700"></p>
<p>For any given individual, across 20,000 trials no assignment exceeds an imbalance of ~2-3%.</p>
<pre><code>## Probability of assignment to group 'a' in 20,000 trials</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.4733  0.4984  0.5001  0.5000  0.5015  0.5181</code></pre>
<pre><code>## Probability of assignment to group 'b' in 20,000 trials</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.4819  0.4985  0.4999  0.5000  0.5016  0.5266</code></pre>
<p>However, in each trial the number of individuals in group A vs. B was random and could be imbalanced.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df_trials &lt;-<span class="st"> </span><span class="kw">gather</span>(assigns, <span class="dt">key =</span> <span class="st">'trial'</span>, <span class="dt">value =</span> <span class="st">'group'</span>, 
                      <span class="kw">starts_with</span>(<span class="st">'group'</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(trial) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="st">`</span><span class="dt">No. group 'a'</span><span class="st">`</span> =<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/sum">sum</a></span>(group <span class="op">==</span><span class="st"> 'a'</span>),
            <span class="st">`</span><span class="dt">No. group 'b'</span><span class="st">`</span> =<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/sum">sum</a></span>(group <span class="op">==</span><span class="st"> 'b'</span>))</code></pre></div>
<pre><code>## No. assigned to group 'a' in 20,000 trials</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   459.0   516.0   527.0   526.9   538.0   588.0</code></pre>
<pre><code>## No assigned to group 'b' in 20,000 trials</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   466.0   516.0   527.0   527.1   538.0   595.0</code></pre>
<p>See how the number assigned varies widely?</p>
<p>what if you want to guarantee an equal number of individuals are in each group?</p>
</div>
<div id="random-assignment-to-k-groups-equal-sample-size" class="section level3">
<h3 class="hasAnchor">
<a href="#random-assignment-to-k-groups-equal-sample-size" class="anchor"></a>Random assignment to K-groups, equal sample size</h3>
<p>We will repeat the exercise, dropping one person to make an odd-numbered cohort.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pidnum &lt;-<span class="st"> </span>df<span class="op">$</span>pidnum 
pidnum &lt;-<span class="st"> </span>pidnum[<span class="dv">2</span><span class="op">:</span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/length">length</a></span>(pidnum)] <span class="co"># drop 1 </span>

n=<span class="dv">10000</span>

seeds &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/sample">sample</a></span>(<span class="op">-</span><span class="dv">100000</span><span class="op">:</span><span class="dv">100000</span>, n)
df_assign &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/lapply">lapply</a></span>(<span class="dv">1</span><span class="op">:</span>n, <span class="cf">function</span>(x) {
  <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/Random">set.seed</a></span>(seeds[x])
  <span class="kw"><a href="../reference/rnd_allot.html">rnd_allot</a></span>(pidnum)
  })

assigns &lt;-<span class="st"> </span><span class="kw">bind_cols</span>(df_assign[[<span class="dv">1</span>]][, <span class="dv">1</span>], 
                     <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/lapply">lapply</a></span>(df_assign, <span class="cf">function</span>(x) x[, <span class="dv">2</span>]))

df_assign_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">gather</span>(assigns, <span class="dt">key =</span> <span class="st">'trial'</span>, <span class="dt">value =</span> <span class="st">'group'</span>, 
                      <span class="kw">starts_with</span>(<span class="st">'group'</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(id) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="st">`</span><span class="dt">No. of trials</span><span class="st">`</span> =<span class="st"> </span>n,
            <span class="st">`</span><span class="dt">No. group 'a'</span><span class="st">`</span> =<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/sum">sum</a></span>(group <span class="op">==</span><span class="st"> 'a'</span>),
            <span class="st">`</span><span class="dt">No. group 'b'</span><span class="st">`</span> =<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/sum">sum</a></span>(group <span class="op">==</span><span class="st"> 'b'</span>),
            <span class="st">`</span><span class="dt">Prob. group = 'a'</span><span class="st">`</span> =<span class="st"> `</span><span class="dt">No. group 'a'</span><span class="st">`</span> <span class="op">/</span><span class="st"> </span><span class="kw">n</span>(),
            <span class="st">`</span><span class="dt">Prob. group = 'b'</span><span class="st">`</span> =<span class="st"> `</span><span class="dt">No. group 'b'</span><span class="st">`</span> <span class="op">/</span><span class="st"> </span><span class="kw">n</span>())

<span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/head">head</a></span>(df_assign_<span class="dv">2</span>)</code></pre></div>
<pre><code>## # A tibble: 6 x 6
##      id `No. of trials` `No. group 'a'` `No. group 'b'` `Prob. group = ~
##   &lt;int&gt;           &lt;dbl&gt;           &lt;int&gt;           &lt;int&gt;            &lt;dbl&gt;
## 1 10140           10000            4958            5042            0.496
## 2 10165           10000            4955            5045            0.496
## 3 10190           10000            5026            4974            0.503
## 4 10229           10000            4959            5041            0.496
## 5 10361           10000            4971            5029            0.497
## 6 10368           10000            4943            5057            0.494
## # ... with 1 more variable: `Prob. group = 'b'` &lt;dbl&gt;</code></pre>
</div>
<div id="assignment-tests" class="section level3">
<h3 class="hasAnchor">
<a href="#assignment-tests" class="anchor"></a>Assignment tests</h3>
<p><img src="03-assignment_files/figure-html/unnamed-chunk-15-1.png" width="700"></p>
<p>Random assignment looks well-balanced between groups.</p>
<pre><code>## Probability of assignment to group 'a' in 20,000 trials</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.4829  0.4965  0.5001  0.5000  0.5035  0.5142</code></pre>
<pre><code>## Probability of assignment to group 'b' in 20,000 trials</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.4858  0.4965  0.4999  0.5000  0.5035  0.5171</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df_trials &lt;-<span class="st"> </span><span class="kw">gather</span>(assigns, <span class="dt">key =</span> <span class="st">'trial'</span>, <span class="dt">value =</span> <span class="st">'group'</span>, 
                      <span class="kw">starts_with</span>(<span class="st">'group'</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(trial) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="st">`</span><span class="dt">No. group 'a'</span><span class="st">`</span> =<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/sum">sum</a></span>(group <span class="op">==</span><span class="st"> 'a'</span>),
            <span class="st">`</span><span class="dt">No. group 'b'</span><span class="st">`</span> =<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/sum">sum</a></span>(group <span class="op">==</span><span class="st"> 'b'</span>))</code></pre></div>
<p>What about the size of the groups?</p>
<pre><code>## No. assigned to group 'a' in 20,000 trials</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   526.0   526.0   526.0   526.5   527.0   527.0</code></pre>
<pre><code>## No assigned to group 'b' in 20,000 trials</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   526.0   526.0   527.0   526.5   527.0   527.0</code></pre>
<p>Equal size! The number now randomly goes between 526 or 527 for either the ‘a’ or ‘b’ group. The imbalance is selected with equal probability.</p>
</div>
</div>
<div id="contacting-authors" class="section level1">
<h1 class="hasAnchor">
<a href="#contacting-authors" class="anchor"></a>Contacting authors</h1>
<p>The primary author of the package was Kevin W. McConeghy. <a href="https://github.com/kmcconeghy/">See here</a></p>
</div>
<div id="references" class="section level1 unnumbered">
<h1 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h1>
<div id="refs" class="references">
<div id="ref-HammerSM1996">
<p>Hammer SM, et al. 1996. “A Trial Comparing Nucleoside Monotherapy with Combination Therapy in Hiv-Infected Adults with Cd4 Cell Counts from 200 to 500 Per Cubic Millimeter.” <em>N Eng J M</em> 335: 1081–90.</p>
</div>
<div id="ref-Mersenne1998">
<p>Matsumoto, M, and T Nishimura. 1998. “Mersenne Twister: A 623-Dimensionally Equidistributed Uniform Pseudo-Random Number Generator.” <em>ACM Transactions on Modeling and Computer Simulation</em> 8: 3–30. <a href="Source%20code%20formerly%20at%20http://www.math.keio.ac.jp/~matumoto/emt.html.%20Now%20see%20http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/VERSIONS/C-LANG/c-lang.html." class="uri">Source code formerly at http://www.math.keio.ac.jp/~matumoto/emt.html. Now see http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/VERSIONS/C-LANG/c-lang.html.</a></p>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#introduction">Introduction</a></li>
      <li><a href="#a-note-on-random-number-generation">A note on random number generation</a></li>
      <li><a href="#random-assignment-to-k-groups">Random assignment to K-groups</a></li>
      <li><a href="#contacting-authors">Contacting authors</a></li>
      <li><a href="#references">References</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Kevin W. McConeghy.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.3.0.</p>
</div>
      </footer>
</div>

  

  </body>
</html>
